server:
  port: 8081
spring:
  application:
    name: account-query-balance
  datasource:
    url: jdbc:h2:../db-balance;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
logging:
  level:
    org.axonframework: debug
    
---
spring:
  profiles: rabbit
application:
  exchange: account.events
  queue: account.balance
axon:
  eventhandling:
    processors:
      balance:
        source: amqpMessageSource
        mode: subscribing
        
---
spring:
  profiles: kafka
axon:
  eventhandling:
    processors:
      balance:
        source: kafkaMessageSource
        mode: tracking
  kafka:
    bootstrap-servers: localhost:9092
    client-id: account-query-balance
    default-topic: account.events
    properties:
      security.protocol: PLAINTEXT
    fetcher:
      poll-timeout: 3000                    #Default value
    consumer:
      group-id: account-query-balance
      enable-auto-commit: true              #Enable auto-commit consumer offsets to the kafka server
      auto-commit-interval: 3000            #Auto-commit interval for consumer offsets

    