server:
  port: 8081
spring:
  application:
    name: account-query-balance
  datasource:
    url: jdbc:h2:../db-balance;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
logging:
  level:
    org.axonframework: debug