global:
  scrape_interval:     10s
  evaluation_interval: 10s
scrape_configs:

- job_name: 'prometheus'
  metrics_path:  '/metrics'
  static_configs:
  - targets: ['localhost:9090']

- job_name: 'rabbitmq'
  metrics_path:  '/metrics'
  static_configs:
  - targets: ['192.168.1.33:15692']
  
- job_name: 'account-command'
  metrics_path:  '/actuator/prometheus'
  static_configs:
  - targets: ['192.168.1.33:8080']
  
- job_name: 'account-balance'
  metrics_path:  '/actuator/prometheus'
  static_configs:
  - targets: ['192.168.1.33:8081']

- job_name: 'account-info'
  metrics_path:  '/actuator/prometheus'
  static_configs:
  - targets: ['192.168.1.33:8082']
  