application:
  axon:
    snapshot:
      threshold: 100
spring:
  application:
    name: account-command 
  datasource:
    url: jdbc:h2:../db-command;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
logging:
  level:
    org.axonframework: debug
    
---        
spring:
  profiles: rabbit
axon:
  amqp:
    exchange: account.events
   
---
spring:
  profiles: kafka
axon:
  kafka:
    bootstrap-servers: localhost:9092
    client-id: account-command
    default-topic: account.events
    properties:
      security.protocol: PLAINTEXT
    producer:
      transaction-id-prefix: account        #Enables kafka's transaction support
    
