server:
  port: 8082
spring:
  application:
    name: account-query-info
  datasource:
    url: jdbc:h2:../db-info;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
logging:
  level:
    org.axonframework: debug
    
---
spring:
  profiles: rabbit
application:
  exchange: account.events
  queue: account.info
axon:
  eventhandling:
    processors:
      info:
        source: amqpMessageSource
        mode: subscribing